apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
<<<<<<< HEAD
        image: nextcloud
=======
        image: nginx
>>>>>>> 767979bc8ef974fa6847ac17253b0a88b2d429a1
        ports:
        - containerPort: 80
